# TODO:
# * run tests
# * coverage
# * analyzers: sanitizers, valgrind, Coverity Scan, CSA

language: c
os: linux
script: scripts/travis.sh
jobs:
  include:
    - stage: baseline
      name: gcc-libclang6
      compiler: gcc
      env:
        - LLVM_CONFIG=llvm-config-6.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - llvm-6.0
            - libclang1-6.0
            - libclang-6.0-dev
            - python3
            - python3-setuptools
            - python3-wheel
      deploy:
        provider: releases
        api_key:
          secure: hdZxL9h1mQbpos3Fhv5Uq0QuHZzWAXbZtEBFnnu+Np82PSN0XwmfMpAiE0DizF1TF/8QXUEBIFFTVD2J3GIqy/HZHTwXz350dvwWUOvKhuXKCCJUBAVTbku4R6zF8M9irhEIoMcWloyxagNLXwDtbxQBHNdnzq+x4P+/NwsHYnDaPhX8cuC3b7is6leGSWRV3qne3Uqp3ILVZsqePfJiReR8oHWTjjoklEXjbbqbpL5HT34XbmeSMMjGaQmUb6+KGrKYaH6VR/xa6xzQDPTYmsctL0gXCc40VxZK4IarabiokUKp17AtYNhbtC4HWTsrmaTXnd7knTj5v4BvfBg9mEf1K4kEWKZD+z0FHDtY1u46Qo6VAFGN/c7Sjo3RyBzL37BVNl+LoyHz+qKXnvEpYlaLB4rnGv01rOXOVnSDKTpT6kK8SpbfTpa14YR5Y7kjkO1LCXm/wdRfs7KCptbzN5tMRGubnZ82pdtYxfN74LckcicfYb4/BnczC67l4VBucbt90Je9xFJGjT6L9vRnSpPFyAbMiQL7LAuRPRONrx5SXla6MKeX9bWsCU6+CdR7n0f7rqtobSeCsJTITOnePHWbDsnWKR7mG3CpaagZ+u+dVTRYuFg1w7SE+ryAwWYDWIsreCcrN+7B2IBdEUEXc4cnBb5tlXIMXIUwe96hzlQ=
        skip_cleanup: true
        file_glob: true
        file:
          - dist/*.whl
          - bin/read_header_api
        on:
          tags: true
    - name: clang-libclang6
      compiler: clang
      env:
        - LLVM_CONFIG=llvm-config-6.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - llvm-6.0
            - libclang1-6.0
            - libclang-6.0-dev
            - python3
            - python3-setuptools
            - python3-wheel
