# TODO:
# * run tests
# * coverage
# * analyzers: sanitizers, valgrind, Coverity Scan, CSA

language: c
os: linux
script: scripts/travis.sh
jobs:
  include:
    - stage: baseline
      name: gcc-libclang6
      compiler: gcc
      env:
        - LLVM_CONFIG=llvm-config-6.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - llvm-6.0
            - libclang1-6.0
            - libclang-6.0-dev
            - python3
            - python3-setuptools
            - python3-wheel
    - name: clang-libclang6
      compiler: clang
      env:
        - LLVM_CONFIG=llvm-config-6.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - llvm-6.0
            - libclang1-6.0
            - libclang-6.0-dev
            - python3
            - python3-setuptools
            - python3-wheel
