# TODO:
# * coverage
# * analyzers: valgrind, CSA
# * deploy

name: CI
on:
  push:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
jobs:
  Baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        cxx: [g++, clang++]
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.cxx }}
      LLVM_CONFIG: llvm-config
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get -y install llvm libclang-dev python3 python3-setuptools python3-wheel
    - name: Run tests
      run: scripts/travis.sh
  Asan:
    runs-on: ubuntu-latest
    env:
      CXX: clang++
      LLVM_CONFIG: llvm-config
      ASAN: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get -y install llvm libclang-dev python3 python3-setuptools python3-wheel
    - name: Run tests
      run: scripts/travis.sh
  UBsan:
    runs-on: ubuntu-latest
    env:
      CXX: clang++
      LLVM_CONFIG: llvm-config
      UBSAN: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get -y install llvm libclang-dev python3 python3-setuptools python3-wheel
    - name: Run tests
      run: scripts/travis.sh
  Coverity:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get -y install llvm libclang-dev python3 python3-setuptools python3-wheel
    - uses: vapier/coverity-scan-action@v0
      with:
        project: yugr%2FShlibVisibilityChecker
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        email: ${{ secrets.EMAIL }}
  Coverage:
    runs-on: ubuntu-latest
    environment: secrets
    env:
      COVERAGE: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      PYTHON: 'coverage run -a'
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo pip3 install codecov
        sudo apt-get -y install llvm libclang-dev python3 python3-setuptools python3-wheel
    - name: Run tests and upload coverage
      run: scripts/travis.sh
