# TODO:
# * proper deploy (with dependencies, etc.)

name: CI
on:
  push:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
  pull_request:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
jobs:
  Baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
        cxx: [g++, clang++]
        py: [python3.6, python3.7, python3]
        exclude:
          - os: ubuntu-22.04
            py: python3.6
    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.cxx }}
      PYTHON: ${{ matrix.py }}
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        scripts/install-deps.sh
    - name: Run tests
      run: scripts/travis.sh
  Pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        scripts/install-deps.sh
        sudo apt-get install pylint
    - name: Run tests
      run: make pylint
  CSA:
    runs-on: ubuntu-latest
    env:
      CXX: clang
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        scripts/install-deps.sh
        sudo apt-get install clang-tools
    - name: Run tests
      run: scan-build --keep-going --status-bugs scripts/travis.sh
  Asan:
    runs-on: ubuntu-latest
    env:
      CXX: clang++
      ASAN: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: scripts/install-deps.sh
    - name: Run tests
      run: scripts/travis.sh
  UBsan:
    runs-on: ubuntu-latest
    env:
      CXX: clang++
      UBSAN: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: scripts/install-deps.sh
    - name: Run tests
      run: scripts/travis.sh
  Valgrind:
    runs-on: ubuntu-latest
    env:
      VALGRIND: 1
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        scripts/install-deps.sh
        sudo apt-get install valgrind
    - name: Run tests
      run: scripts/travis.sh
  Coverage:
    needs: Baseline
    runs-on: ubuntu-latest
    environment: secrets
    env:
      COVERAGE: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        scripts/install-deps.sh
        sudo python3 -m pip install codecov
    - name: Run tests and upload coverage
      env:
        PYTHON: coverage run -a
      run: scripts/travis.sh
